### ISSUE TITLE
Invalid version string does not result in `InvalidVersion` exception

### ISSUE THREAD

**Issue by dsentker** [ergebnis/version#14]
When using a dot only as pre-release identifier, the regular expression matches a false positive.

#### Steps required to reproduce the problem

```php
$version = Version::fromString('1.2.3-.+b');
```

#### Expected Result
`Exception\InvalidVersion` is thrown

#### Actual Result
Current implementation is happy with this input

**Background**
According to semver.org, a valid pre-release identifier is an numeric or alphanumeric character. 
```
<pre-release identifier> ::= <alphanumeric identifier> | <numeric identifier>
```

Because the period is recognized as a valid string of the prerelease part, it is a valid character in the `Ergebnis\Version\Version::REGEX`. Strictly speaking, the Prerelease part must consist of one or more valid Prerelease strings, each separated by a period. It seems insufficient to use just a dot as a prerelease.

That might be an edge case, so i am happy with closing the issue, too.

```
<dot-separated pre-release identifiers> ::= <pre-release identifier>
                                          | <pre-release identifier> "." <dot-separated pre-release identifiers>
```

**Comment by localheinz** [comment]
Looks like #15 passes, what do you think?

**Comment by dsentker** [comment]
Oh no, I don't know what I tested there. The string I mentioned is correctly recognized as invalid. I'm sorry.

**Comment by localheinz** [comment]
Thank you, @dsentker!
