### ISSUE TITLE
Use native `version_compare()` for `Version::compare()`

### ISSUE THREAD

**Issue by dsentker** [ergebnis/version#26]
It is possible to reduce code complexity (and LLoC) when using [version_compare](https://www.php.net/manual/en/function.version-compare.php) for the logic in `Version::compare()`.

This can be done with creating both version objects as string, without metadata or prerelease and then using this strings for the native php function. What do you think?

**Comment by localheinz** [comment]
Not sure, what do you think about #27, @dsentker?

**Comment by dsentker** [comment]
Not sure TBH, i re-read the semver specification and found it that comparing prerelease information is actually a thing. 

[Here is a proposal](https://github.com/ergebnis/version/pull/27#issuecomment-1870434785) for making your solution cleaner.
